# Generated by Django 6.0.4 on 2026-04-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('cards_reviewed', models.IntegerField(default=0, verbose_name='Просмотрено карточек')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='Правильных ответов')),
                ('max_streak', models.IntegerField(default=0, verbose_name='Максимальная серия')),
            ],
            options={
                'verbose_name': 'Статистика тренировки',
                'verbose_name_plural': 'Статистика тренировок',
                'ordering': ['-date'],
            },
        ),
    ]
