# Generated by Django 6.0.4 on 2026-04-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_studystats'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='source',
            field=models.CharField(default='db', max_length=50, verbose_name='Источник'),
        ),
    ]
